[package]
name = "video_core"
version.workspace = true
edition.workspace = true

[dependencies]
common.workspace = true
ruzu_core = { package = "core", path = "../core" }
shader_recompiler.workspace = true
gl.workspace = true
log.workspace = true
thiserror.workspace = true
anyhow.workspace = true
vulkano.workspace = true
ash.workspace = true
vk-mem.workspace = true
raw-window-handle.workspace = true
parking_lot.workspace = true
rspirv.workspace = true
spirv.workspace = true
bitflags.workspace = true
bytemuck.workspace = true
libc = "0.2"
smallvec = { version = "1", features = ["const_generics"] }
rxbyak = { path = "../../externals/rxbyak" }

[target.'cfg(target_os = "macos")'.dependencies]
objc2.workspace = true
objc2-metal.workspace = true
objc2-quartz-core.workspace = true
objc2-foundation.workspace = true
spirv-cross2.workspace = true

[build-dependencies]
cc = "1"
pkg-config = "0.3"
